# Generated by Django 3.2.11 on 2023-01-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=255)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('check', models.BooleanField(default=False)),
            ],
        ),
    ]
